from axis3.engine.game_loop import game_loop
from axis3.engine.ui.cli import CLI
from axis3.engine.loader.loader import build_game_state_from_decks
from axis2.builder import Axis2Builder
from axis1.schema import Axis1Card, Axis1Face, Axis1Characteristics, Axis1SearchIndex
from axis3.rules.events.types import EventType
from axis3.rules.handlers.cast_handlers import handle_cast_spell
from axis3.rules.handlers.untap_handler import handle_untap_event
from axis3.engine.turn.turn_manager import TurnManager

def load_test_decks():
    forest_face = Axis1Face(
        face_id="front",
        name="Forest",
        type_line="Basic Land — Forest",
        mana_cost=None,
        mana_value=None,
        card_types=["Land"],
        supertypes=["Basic"],
        subtypes=["Forest"],
        colors=[],
        oracle_text="({T}: Add {G}.)",
        produced_mana=["G"],
    )
    forest = Axis1Card(
        card_id="forest-001",
        layout="normal",
        object_kind="card",
        name="Forest",
        names=["Forest"],
        type_line="Basic Land — Forest",
        oracle_text="({T}: Add {G}.)",
        mana_cost=None,
        mana_value=None,
        colors=[],
        color_identity=["G"],
        keywords=[],
        produced_mana=["G"],
        power=None,
        toughness=None,
        loyalty=None,
        defense=None,
        released_at=None,
        faces=[forest_face],
        characteristics=Axis1Characteristics(
            mana_cost=None,
            mana_value=None,
            type_line="Basic Land — Forest",
            colors=[],
            color_identity=["G"],
            card_types=["Land"],
            supertypes=["Basic"],
            subtypes=["Forest"],
            power=None,
            toughness=None,
            loyalty=None,
            defense=None,
        ),
        search_index=Axis1SearchIndex(
            name="Forest",
            names=["Forest"],
            type_line="Basic Land — Forest",
            colors=[],
            color_identity=["G"],
            card_types=["Land"],
            supertypes=["Basic"],
            subtypes=["Forest"],
            keywords=[],
            produced_mana=["G"],
            mana_value=None,
            power=None,
            toughness=None,
            loyalty=None,
            defense=None,
            rarity=None,
            set_code=None,
            set_name=None,
            set_type=None,
            layout="normal",
            released_at=None,
            oracle_text="({T}: Add {G}.)",
        ),
    )
    
    forest2 = Axis1Card(
        card_id="forest-002",
        layout="normal",
        object_kind="card",
        name="Forest",
        names=["Forest"],
        type_line="Basic Land — Forest",
        oracle_text="({T}: Add {G}.)",
        mana_cost=None,
        mana_value=None,
        colors=[],
        color_identity=["G"],
        keywords=[],
        produced_mana=["G"],
        power=None,
        toughness=None,
        loyalty=None,
        defense=None,
        released_at=None,
        faces=[forest_face],
        characteristics=Axis1Characteristics(
            mana_cost=None,
            mana_value=None,
            type_line="Basic Land — Forest",
            colors=[],
            color_identity=["G"],
            card_types=["Land"],
            supertypes=["Basic"],
            subtypes=["Forest"],
            power=None,
            toughness=None,
            loyalty=None,
            defense=None,
        ),
        search_index=Axis1SearchIndex(
            name="Forest",
            names=["Forest"],
            type_line="Basic Land — Forest",
            colors=[],
            color_identity=["G"],
            card_types=["Land"],
            supertypes=["Basic"],
            subtypes=["Forest"],
            keywords=[],
            produced_mana=["G"],
            mana_value=None,
            power=None,
            toughness=None,
            loyalty=None,
            defense=None,
            rarity=None,
            set_code=None,
            set_name=None,
            set_type=None,
            layout="normal",
            released_at=None,
            oracle_text="({T}: Add {G}.)",
        ),
    )

    bear_face = Axis1Face(
        face_id="front",
        name="Grizzly Bears",
        type_line="Creature — Bear",
        mana_cost="{1}{G}",
        mana_value=2,
        colors=["G"],
        color_indicator=[],
        card_types=["Creature"],
        supertypes=[],
        subtypes=["Bear"],
        power="2",
        toughness="2",
        loyalty=None,
        defense=None,
        oracle_text="",
        printed_text=None,
        flavor_text=None,
        keywords=[],
        ability_words=[],
        static_abilities=[],
        reminder_text=[],
        has_characteristic_defining_abilities=False,
        characteristic_defining_abilities=[],
        intrinsic_counters=[],
        attachment=None,
    )
    bear = Axis1Card(
        card_id="bear-001",
        layout="normal",
        object_kind="card",
        name="Grizzly Bears",
        names=["Grizzly Bears"],
        type_line="Creature — Bear",
        oracle_text="",
        mana_cost="{1}{G}",
        mana_value=2,
        colors=["G"],
        color_identity=["G"],
        keywords=[],
        produced_mana=[],
        power="2",
        toughness="2",
        loyalty=None,
        defense=None,
        released_at=None,
        faces=[bear_face],
        characteristics=Axis1Characteristics(
            mana_cost="{1}{G}",
            mana_value=2,
            type_line="Creature — Bear",
            colors=["G"],
            color_identity=["G"],
            card_types=["Creature"],
            supertypes=[],
            subtypes=["Bear"],
            power="2",
            toughness="2",
            loyalty=None,
            defense=None,
        ),
        search_index=Axis1SearchIndex(
            name="Grizzly Bears",
            names=["Grizzly Bears"],
            type_line="Creature — Bear",
            colors=["G"],
            color_identity=["G"],
            card_types=["Creature"],
            supertypes=[],
            subtypes=["Bear"],
            keywords=[],
            produced_mana=[],
            mana_value=2,
            power="2",
            toughness="2",
            loyalty=None,
            defense=None,
            rarity=None,
            set_code=None,
            set_name=None,
            set_type=None,
            layout="normal",
            released_at=None,
            oracle_text="",
        ),
    )


    return [forest, forest, forest2, bear, forest2, bear, forest2, bear, forest2, bear], [forest, forest2, forest, bear, forest2, bear, forest, bear, forest, bear]

def main():
    deck1, deck2 = load_test_decks()
    axis2_builder = Axis2Builder()

    game_state = build_game_state_from_decks(
        deck1,
        deck2,
        axis2_builder
    )

    game_state.turn_manager = TurnManager(game_state)
    ui = CLI()
    game_loop(game_state, ui)

if __name__ == "__main__":
    main()
